config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#index"

  resources :campaigns do
    resources :player_characters, controller: "campaigns/player_characters"
    resources :non_player_characters, controller: "campaigns/non_player_characters"
    resources :cities, controller: "campaigns/cities"
    resources :factions, controller: "campaigns/factions"
    resources :storylines, controller: "campaigns/storylines"
    resources :quests, controller: "campaigns/quests"
  end
end

app/models/campaign.rb
# == Schema Information
#
# Table name: campaigns
#
#  id          :bigint           not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_campaigns_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Campaign < ApplicationRecord
  default_scope { order(updated_at: :desc) }

  belongs_to :user

  has_many :player_characters
  has_many :non_player_characters
  has_many :cities
  has_many :storylines
  has_many :quests

  validates :title, presence: true
  validates :description, presence: true

  def last_updated
    (DateTime.now.to_f - updated_at.to_f).to_i / 60
  end
end

app/models/character.rb
# == Schema Information
#
# Table name: characters
#
#  id               :bigint           not null, primary key
#  backstory        :text
#  challenge_rating :integer
#  character_class  :string
#  charisma         :integer
#  constitution     :integer
#  dexterity        :integer
#  intelligence     :integer
#  level            :integer
#  name             :string
#  race             :string
#  sheet_url        :string
#  strength         :integer
#  type             :string
#  wisdom           :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  alignment_id     :bigint           not null
#  campaign_id      :bigint           not null
#  monster_type_id  :bigint
#  size_category_id :bigint           not null
#
# Indexes
#
#  index_characters_on_alignment_id      (alignment_id)
#  index_characters_on_campaign_id       (campaign_id)
#  index_characters_on_monster_type_id   (monster_type_id)
#  index_characters_on_size_category_id  (size_category_id)
#
# Foreign Keys
#
#  fk_rails_...  (alignment_id => alignments.id)
#  fk_rails_...  (campaign_id => campaigns.id)
#  fk_rails_...  (monster_type_id => monster_types.id)
#  fk_rails_...  (size_category_id => size_categories.id)
#
class Character < ApplicationRecord
  FILE_VALIDATIONS = {
    content_types: %w[image/png image/jpeg image/gif],
    max_size: 5.megabytes,
  }.freeze

  belongs_to :campaign
  belongs_to :size_category
  belongs_to :alignment

  has_one_attached :icon, dependent: :destroy

  validate :valid_icon_mime, :valid_icon_size

  validates :strength,
    :dexterity,
    :constitution,
    :intelligence,
    :wisdom,
    :charisma, numericality: { greater_than: 0, less_than_or_equal_to: 30 },
    presence: true

  validates :name, :race, presence: true

  private

  def valid_icon_mime
    if icon.attached? && !icon.content_type.in?(FILE_VALIDATIONS[:content_types])
      errors.add(:icon, "Must be one of #{FILE_VALIDATIONS[:content_types].join(', ')}")
    end
  end

  def valid_icon_size
    if icon.attached? && FILE_VALIDATIONS[:max_size] < icon.attachment.blob.byte_size
      errors.add(:icon, "Must be smaller than 5MB")
    end
  end
end

app/controllers/campaigns/base_controller.rb
class Campaigns::BaseController < ApplicationController
  before_action :is_current_user

  def set_campaign
    @campaign = Campaign.find(params[:campaign_id])
  end
end

app/controllers/campaigns/cities_controller.rb
class Campaigns::CitiesController < Campaigns::BaseController
  before_action :set_campaign
  before_action :set_city

  def index
    add_breadcrumb(@campaign.title.downcase, campaign_path(@campaign))
    add_breadcrumb("cities", campaign_cities_path(@campaign), true)
  end

  def show
    add_breadcrumb(@campaign.title.downcase, campaign_path(@campaign))
    add_breadcrumb("cities", campaign_cities_path(@campaign))
    add_breadcrumb(@city.name, campaign_city_path(@campaign, @city), true)

    render(CityComponent.new(city: @city))
  end

  def new
    add_breadcrumb(@campaign.title.downcase, campaign_path(@campaign))
    add_breadcrumb("cities", campaign_cities_path(@campaign))
    add_breadcrumb("new", new_campaign_city_path(@campaign), true)
  end

  def edit
    add_breadcrumb(@campaign.title.downcase, campaign_path(@campaign))
    add_breadcrumb("cities", campaign_cities_path(@campaign))
    add_breadcrumb("edit", edit_campaign_city_path(@campaign, @city), true)
  end

  def create
    @city.assign_attributes(city_params)
    if @city.save
      flash[:success] = "#{@city.name} was created and added to your campaign"
      redirect_to campaign_city_path(@campaign, @city)
    else
      flash[:error] = @city.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @city.assign_attributes(city_params)
    if @city.save
      flash[:success] = "#{@city.name} updated"
      redirect_to campaign_city_path(@campaign, @city)
    else
      flash[:error] = @city.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @city.destroy
      flash[:notice] = "City deleted"
    else
      flash[:error] = @city.errors.full_messages.to_sentence
    end
    redirect_to campaign_path(@campaign)
  end

  private

  def set_city
    @city = params[:id] ? City.find(params[:id]) : City.new(campaign: @campaign)
  end

  def city_params
    params.require(:city).permit(
      :name,
      :description,
      :gov_type,
      :population,
      :leader_id
    )
  end
end

app/controllers/campaigns/non_player_characters_controller.rb
class Campaigns::NonPlayerCharactersController < Campaigns::BaseController
  before_action :set_campaign
  before_action :set_non_player_character

  def new
  end

  def edit
  end

  def create
    @non_player_character.assign_attributes(non_player_character_params)
    if @non_player_character.save
      flash[:success] = "#{@non_player_character.name} was created and added to your campaign"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @non_player_character.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @non_player_character.assign_attributes(non_player_character_params)
    if @non_player_character.save
      flash[:success] = "#{@non_player_character.name} updated"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @non_player_character.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @non_player_character.destroy
      flash[:notice] = "Non-Player Character deleted"
    else
      flash[:error] = @non_player_character.errors.full_messages.to_sentence
    end
    redirect_to campaign_path(@campaign)
  end

  private

  def set_non_player_character
    @non_player_character = params[:id] ? NonPlayerCharacter.find(params[:id]) : NonPlayerCharacter.new(campaign: @campaign)
  end

  def non_player_character_params
    params.require(:non_player_character).permit(
      :name,
      :race,
      :stat_block_url,
      :alignment_id,
      :backstory,
      :challenge_rating,
      :size_category_id,
      :monster_type_id
    )
  end
end

app/controllers/campaigns/player_characters_controller.rb
class Campaigns::PlayerCharactersController < Campaigns::BaseController
  before_action :set_campaign
  before_action :set_player_character, except: %i[index]

  def index
    add_breadcrumb(@campaign.title.downcase, campaign_path(@campaign))
    add_breadcrumb("player characters", campaign_player_characters_path(@campaign), true)
  end

  def show
    add_breadcrumb(@campaign.title, campaign_path(@campaign))
    add_breadcrumb("player characters", campaign_player_characters_path(@campaign))
    add_breadcrumb(@player_character.name, campaign_player_character_path(@campaign, @player_character), true)
  end

  def new
    add_breadcrumb(@campaign.title, campaign_path(@campaign))
    add_breadcrumb("player characters", campaign_player_characters_path(@campaign))
    add_breadcrumb("new", new_campaign_player_character_path(@campaign), true)
  end

  def edit
    add_breadcrumb(@campaign.title, campaign_path(@campaign))
    add_breadcrumb("player characters", campaign_player_characters_path(@campaign))
    add_breadcrumb("edit", edit_campaign_player_character_path(@campaign, @player_character), true)
  end

  def create
    @player_character.assign_attributes(player_character_params)
    if @player_character.save
      flash[:success] = "#{@player_character.name} was created and added to your campaign"
      redirect_to campaign_player_character_path(@campaign, @player_character)
    else
      flash[:error] = @player_character.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @player_character.assign_attributes(player_character_params)
    if @player_character.save
      flash[:success] = "#{@player_character.name} updated"
      redirect_to campaign_player_character_path(@campaign, @player_character)
    else
      flash[:error] = @player_character.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @player_character.destroy
      flash[:notice] = "Player Character deleted"
    else
      flash[:error] = @player_character.errors.full_messages.to_sentence
    end
    redirect_to campaign_path(@campaign)
  end

  private

  def set_player_character
    @player_character = params[:id] ? PlayerCharacter.find(params[:id]) : PlayerCharacter.new(campaign: @campaign)
  end

  def player_character_params
    params.require(:player_character).permit(
      :name,
      :race,
      :sheet_url,
      :level,
      :strength,
      :dexterity,
      :constitution,
      :intelligence,
      :wisdom,
      :charisma,
      :character_class,
      :icon,
      :alignment_id,
      :size_category_id
    )
  end
end

app/controllers/campaigns/quests_controller.rb
class Campaigns::QuestsController < Campaigns::BaseController
  before_action :set_campaign
  before_action :set_quest, except: %i[index]

  def index; end

  def new; end

  def edit; end

  def create
    @quest.create_quest(quest_params, params[:quest][:storyline_quests_attributes])
    if @quest.save
      flash[:success] = "#{@quest.name} was created and added to your campaign"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @quest.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    @quest.assign_attributes(quest_params)
    if @quest.save
      flash[:success] = "#{@quest.name} updated"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @quest.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @quest.destroy
      flash[:notice] = 'Quest deleted'
    else
      flash[:error] = @quest.errors.full_messages.to_sentence
    end
    redirect_to campaign_path(@campaign)
  end

  private
    def set_quest
      @quest = params[:id] ? Quest.find(params[:id]) : Quest.new(campaign: @campaign)
    end

    def quest_params
      params.require(:quest).permit(
        :name,
        :description,
        :rewards
      )
    end
end

app/controllers/campaigns/storylines_controller.rb
class Campaigns::StorylinesController < Campaigns::BaseController
  before_action :set_campaign
  before_action :set_storyline, except: %i[index]

  def index; end

  def new; end

  def edit; end

  def create
    @storyline.assign_attributes(storyline_params)
    if @storyline.save
      flash[:success] = "#{@storyline.name} was created and added to your campaign"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @storyline.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    @storyline.assign_attributes(storyline_params)
    if @storyline.save
      flash[:success] = "#{@storyline.name} updated"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @storyline.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @storyline.destroy
      flash[:notice] = 'Storyline deleted'
    else
      flash[:error] = @storyline.errors.full_messages.to_sentence
    end
    redirect_to campaign_path(@campaign)
  end

  private
    def set_storyline
      @storyline = params[:id] ? Storyline.find(params[:id]) : Storyline.new(campaign: @campaign)
    end

    def storyline_params
      params.require(:storyline).permit(
        :name,
        :description
      )
    end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :is_current_user
  before_action :set_campaign, except: %i[index]

  def index
    add_breadcrumb("campaigns", campaigns_path, true)

    @pagy, @campaigns = pagy(current_user.campaigns.order(updated_at: :desc), items: params[:items])
  end

  def show
    add_breadcrumb("campaigns", campaigns_path)
    add_breadcrumb(@campaign.title, campaign_path(@campaign), true)
  end

  def new
    add_breadcrumb("campaigns", campaigns_path)
  end

  def edit
    add_breadcrumb("campaigns", campaigns_path)
  end

  def create
    @campaign.assign_attributes(campaign_params)
    if @campaign.save
      flash[:success] = "Campaign #{params[:action]}d"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @campaign.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @campaign.assign_attributes(campaign_params)
    if @campaign.save
      flash[:notice] = "Campaign #{params[:action]}d"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @campaign.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @campaign.destroy
      flash[:notice] = "Campaign deleted"
    else
      flash[:error] = @campaign.errors.full_messages.to_sentence
    end
    redirect_to campaigns_path
  end

  private

  def set_campaign
    @campaign = params[:id] ? Campaign.find(params[:id]) : Campaign.new(user: current_user)
  end

  def campaign_params
    params.require(:campaign).permit(
      :title,
      :description
    )
  end
end

app/views/campaigns/characters/_form.html.erb
  <h1>Create a New <%= resource.class.name.titleize %></h1>
  <div class='form-container m-2'>
    <div class="form-group m-2 text-center">
      <label for="#name"><%= resource.class.name.titleize %> Name <sup class='text-danger'>* required</sup></label>
      <%= form.text_field :name, placeholder: "#{resource.class.name.titleize} Name", class: "form-control" %>
    </div>

    <div class="form-group m-2 text-center">
      <label for="#race"><%= resource.class.name.titleize %> Race <sup class='text-danger'>* required</sup></label>
      <%= form.text_field :race, placeholder: "#{resource.class.name.titleize} Race", class: "form-control" %>
    </div>

    <div class="form-group m-2 text-center">
      <label for="#character_sheet_url">Character Sheet Url</label>
      <%= form.text_field :sheet_url, placeholder: "Sheet Url", class: "form-control" %>
    </div>

    <% if resource.is_a?(PlayerCharacter) %>
      <div class="form-group m-2 text-center">
        <label for="#level"><%= resource.class.name.titleize %>Level <sup class='text-danger'>* required</sup></label>
        <%= form.select :level, options_for_select(1..20, resource.level || 1), {include_blank: 'Level'}, {class: 'form-control',} %>
      </div>

      <div class="form-group m-2 text-center">
        <label for="#character_class"><%= resource.class.name.titleize %> Class <sup class='text-danger'>* required</sup></label>
        <%= form.text_field :character_class, placeholder: "#{resource.class.name.titleize} Class", class: "form-control" %>
      </div>
    <% end %>

   <div class="form-group m-2 text-center">
      <div class='stat-container'>
        <div class='stat m-2'>
          <label for="#alignment_id">Alignment</label>
          <%= form.collection_select :alignment_id, Alignment.all, :id, :name, {include_blank: 'Select Alignment'}, {multiple: false, class: 'form-control stat-select'} %>
        </div>
        <div class='stat m-2'>
          <label for="#size_category_id">Size</label>
          <%= form.collection_select :size_category_id, SizeCategory.all, :id, :name, {include_blank: 'Select Size'}, {multiple: false, class: 'form-control stat-select'} %>
        </div>
        <div class='stat m-2'>
          <label for="#monster_type_id">Type</label>
          <%= form.collection_select :monster_type_id, MonsterType.all, :id, :name, {include_blank: 'Select Type'}, {multiple: false, class: 'form-control stat-select'} %>
        </div>
        <% if resource.is_a?(NonPlayerCharacter) %>
          <div class='stat m-2'>
            <label for="#challenge_rating">Challenge Rating</label>
            <%= form.text_field :challenge_rating, {class: 'form-control',} %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="form-group m-2 text-center">
      <label><%= resource.class.name.titleize %> Stats</label>
      <div class='stat-container'>
        <div class='stat m-2'>
          <label for="#strength">Strength <sup class='text-danger'>* required</sup></label>
          <%= form.number_field :strength, {class: 'form-control stat-select', min: 0, max: 30} %>
        </div>
        <div class='stat m-2'>
          <label for="#dexterity">Dexterity <sup class='text-danger'>* required</sup></label>
          <%= form.number_field :dexterity, {class: 'form-control stat-select', min: 0, max: 30} %>
        </div>
        <div class='stat m-2'>
          <label for="#constitution">Constitution <sup class='text-danger'>* required</sup></label>
          <%= form.number_field :constitution, {class: 'form-control stat-select', min: 0, max: 30} %>
        </div>
      </div>
      <div class='stat-container'>
        <div class='stat m-2'>
          <label for="#intelligence">Intelligence <sup class='text-danger'>* required</sup></label>
          <%= form.number_field :intelligence, {class: 'form-control stat-select', min: 0, max: 30} %>
        </div>
        <div class='stat m-2'>
          <label for="#wisdom">Wisdom <sup class='text-danger'>* required</sup></label>
          <%= form.number_field :wisdom, {class: 'form-control stat-select', min: 0, max: 30} %>
        </div>
        <div class='stat m-2'>
          <label for="#charisma">Charisma <sup class='text-danger'>* required</sup></label>
          <%= form.number_field :charisma, {class: 'form-control stat-select', min: 0, max: 30} %>
        </div>
      </div>

      <div class="image-upload">
        <% if resource.icon.attached? %>
          <%= image_tag resource.icon.variant(resize: "150 x 150") %>
        <% end %>
        <%= form.file_field :icon, multiple: false, accept: 'image/png,image/gif,image/jpeg' %>
      </div>
    </div>

    <div class="form-group m-1 text-center">
      <%= form.submit  class: 'btn btn-primary' %>
    </div>
  </div>

app/views/campaigns/characters/_show.html.erb
<div class='page-wrapper PlayerCharacter'>
  <div class='header text-center'>
    <h1><%= resource.name %></h1>
    <% if resource.icon.attached? %>
      <%= image_tag resource.icon.variant(resize: "200 x 200") %>
    <% end %>
    <p><%= "Level #{resource.level} #{resource.race} #{resource.character_class}" %></p>
  </div>
  <div class="page-header-end pb-2">
    <% if resource.is_a?(PlayerCharacter) %>
      <%= link_to 'Edit', edit_campaign_player_character_path(@campaign, resource), class: 'btn btn-primary' %>
    <% else %>
      <%= link_to 'Edit', edit_campaign_non_player_character_path(@campaign, resource), class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div class="body">
    <div class="card-group pb-2">
      <div class="double-card card">
        <div class="card-header text-center">
          <h2>Character Statistics</h2>
        </div>
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <% resource.character_stats.each do |k, v| %>
              <li class="list-group-item"><%= "#{k.titlecase}: #{v}" %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="double-card card">
        <div class="card-header text-center">
          <h2>Character Info</h2>
        </div>
        <div class="card-body">
          <ul class="list-group list-group-flush">
          </ul>
        </div>
      </div>
    </div>
    <div class="single-card card text-center">
      <% if resource.sheet_url.present? %>
        <iframe class="character-sheet-frame" src="<%= resource.sheet_url %>" frameborder="0"></iframe>
      <% else %>
        <p>No character sheet attached</p>
      <% end %>
    </div>
  </div>
</div>