config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#index"

  resources :campaigns do
    resources :player_characters, controller: "campaigns/player_characters"
    resources :non_player_characters, controller: "campaigns/non_player_characters"
    resources :cities, controller: "campaigns/cities"
    resources :factions, controller: "campaigns/factions"
    resources :storylines, controller: "campaigns/storylines"
    resources :quests, controller: "campaigns/quests"
  end
end

app/models/campaign.rb
# == Schema Information
#
# Table name: campaigns
#
#  id          :bigint           not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_campaigns_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Campaign < ApplicationRecord
  default_scope { order(updated_at: :desc) }

  belongs_to :user

  has_many :player_characters
  has_many :non_player_characters
  has_many :cities
  has_many :storylines
  has_many :quests

  validates :title, presence: true
  validates :description, presence: true

  def last_updated
    (DateTime.now.to_f - updated_at.to_f).to_i / 60
  end
end

app/controllers/campaigns/base_controller.rb
class Campaigns::BaseController < ApplicationController
  before_action :is_current_user

  def set_campaign
    @campaign = Campaign.find(params[:campaign_id])
  end
end

app/controllers/campaigns/cities_controller.rb
class Campaigns::CitiesController < Campaigns::BaseController
  before_action :set_campaign
  before_action :set_city

  def index
    add_breadcrumb(@campaign.title.downcase, campaign_path(@campaign))
    add_breadcrumb("cities", campaign_cities_path(@campaign), true)
  end

  def show
    add_breadcrumb(@campaign.title.downcase, campaign_path(@campaign))
    add_breadcrumb("cities", campaign_cities_path(@campaign))
    add_breadcrumb(@city.name, campaign_city_path(@campaign, @city), true)

    render(CityComponent.new(city: @city))
  end

  def new
    add_breadcrumb(@campaign.title.downcase, campaign_path(@campaign))
    add_breadcrumb("cities", campaign_cities_path(@campaign))
    add_breadcrumb("new", new_campaign_city_path(@campaign), true)
  end

  def edit
    add_breadcrumb(@campaign.title.downcase, campaign_path(@campaign))
    add_breadcrumb("cities", campaign_cities_path(@campaign))
    add_breadcrumb("edit", edit_campaign_city_path(@campaign, @city), true)
  end

  def create
    @city.assign_attributes(city_params)
    if @city.save
      flash[:success] = "#{@city.name} was created and added to your campaign"
      redirect_to campaign_city_path(@campaign, @city)
    else
      flash[:error] = @city.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @city.assign_attributes(city_params)
    if @city.save
      flash[:success] = "#{@city.name} updated"
      redirect_to campaign_city_path(@campaign, @city)
    else
      flash[:error] = @city.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @city.destroy
      flash[:notice] = "City deleted"
    else
      flash[:error] = @city.errors.full_messages.to_sentence
    end
    redirect_to campaign_path(@campaign)
  end

  private

  def set_city
    @city = params[:id] ? City.find(params[:id]) : City.new(campaign: @campaign)
  end

  def city_params
    params.require(:city).permit(
      :name,
      :description,
      :gov_type,
      :population,
      :leader_id
    )
  end
end

app/controllers/campaigns/non_player_characters_controller.rb
class Campaigns::NonPlayerCharactersController < Campaigns::BaseController
  before_action :set_campaign
  before_action :set_non_player_character

  def new
  end

  def edit
  end

  def create
    @non_player_character.assign_attributes(non_player_character_params)
    if @non_player_character.save
      flash[:success] = "#{@non_player_character.name} was created and added to your campaign"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @non_player_character.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @non_player_character.assign_attributes(non_player_character_params)
    if @non_player_character.save
      flash[:success] = "#{@non_player_character.name} updated"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @non_player_character.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @non_player_character.destroy
      flash[:notice] = "Non-Player Character deleted"
    else
      flash[:error] = @non_player_character.errors.full_messages.to_sentence
    end
    redirect_to campaign_path(@campaign)
  end

  private

  def set_non_player_character
    @non_player_character = params[:id] ? NonPlayerCharacter.find(params[:id]) : NonPlayerCharacter.new(campaign: @campaign)
  end

  def non_player_character_params
    params.require(:non_player_character).permit(
      :name,
      :race,
      :stat_block_url,
      :alignment_id,
      :backstory,
      :challenge_rating,
      :size_category_id,
      :monster_type_id
    )
  end
end

app/controllers/campaigns/player_characters_controller.rb
class Campaigns::PlayerCharactersController < Campaigns::BaseController
  before_action :set_campaign
  before_action :set_player_character, except: %i[index]

  def index
    add_breadcrumb(@campaign.title.downcase, campaign_path(@campaign))
    add_breadcrumb("player characters", campaign_player_characters_path(@campaign), true)
  end

  def show
    add_breadcrumb(@campaign.title, campaign_path(@campaign))
    add_breadcrumb("player characters", campaign_player_characters_path(@campaign))
    add_breadcrumb(@player_character.name, campaign_player_character_path(@campaign, @player_character), true)
  end

  def new
    add_breadcrumb(@campaign.title, campaign_path(@campaign))
    add_breadcrumb("player characters", campaign_player_characters_path(@campaign))
    add_breadcrumb("new", new_campaign_player_character_path(@campaign), true)
  end

  def edit
    add_breadcrumb(@campaign.title, campaign_path(@campaign))
    add_breadcrumb("player characters", campaign_player_characters_path(@campaign))
    add_breadcrumb("edit", edit_campaign_player_character_path(@campaign, @player_character), true)
  end

  def create
    @player_character.assign_attributes(player_character_params)
    if @player_character.save
      flash[:success] = "#{@player_character.name} was created and added to your campaign"
      redirect_to campaign_player_character_path(@campaign, @player_character)
    else
      flash[:error] = @player_character.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @player_character.assign_attributes(player_character_params)
    if @player_character.save
      flash[:success] = "#{@player_character.name} updated"
      redirect_to campaign_player_character_path(@campaign, @player_character)
    else
      flash[:error] = @player_character.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @player_character.destroy
      flash[:notice] = "Player Character deleted"
    else
      flash[:error] = @player_character.errors.full_messages.to_sentence
    end
    redirect_to campaign_path(@campaign)
  end

  private

  def set_player_character
    @player_character = params[:id] ? PlayerCharacter.find(params[:id]) : PlayerCharacter.new(campaign: @campaign)
  end

  def player_character_params
    params.require(:player_character).permit(
      :name,
      :race,
      :sheet_url,
      :level,
      :strength,
      :dexterity,
      :constitution,
      :intelligence,
      :wisdom,
      :charisma,
      :character_class,
      :icon,
      :alignment_id,
      :size_category_id
    )
  end
end

app/controllers/campaigns/quests_controller.rb
class Campaigns::QuestsController < Campaigns::BaseController
  before_action :set_campaign
  before_action :set_quest, except: %i[index]

  def index; end

  def new; end

  def edit; end

  def create
    @quest.create_quest(quest_params, params[:quest][:storyline_quests_attributes])
    if @quest.save
      flash[:success] = "#{@quest.name} was created and added to your campaign"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @quest.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    @quest.assign_attributes(quest_params)
    if @quest.save
      flash[:success] = "#{@quest.name} updated"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @quest.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @quest.destroy
      flash[:notice] = 'Quest deleted'
    else
      flash[:error] = @quest.errors.full_messages.to_sentence
    end
    redirect_to campaign_path(@campaign)
  end

  private
    def set_quest
      @quest = params[:id] ? Quest.find(params[:id]) : Quest.new(campaign: @campaign)
    end

    def quest_params
      params.require(:quest).permit(
        :name,
        :description,
        :rewards
      )
    end
end

app/controllers/campaigns/storylines_controller.rb
class Campaigns::StorylinesController < Campaigns::BaseController
  before_action :set_campaign
  before_action :set_storyline, except: %i[index]

  def index; end

  def new; end

  def edit; end

  def create
    @storyline.assign_attributes(storyline_params)
    if @storyline.save
      flash[:success] = "#{@storyline.name} was created and added to your campaign"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @storyline.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    @storyline.assign_attributes(storyline_params)
    if @storyline.save
      flash[:success] = "#{@storyline.name} updated"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @storyline.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @storyline.destroy
      flash[:notice] = 'Storyline deleted'
    else
      flash[:error] = @storyline.errors.full_messages.to_sentence
    end
    redirect_to campaign_path(@campaign)
  end

  private
    def set_storyline
      @storyline = params[:id] ? Storyline.find(params[:id]) : Storyline.new(campaign: @campaign)
    end

    def storyline_params
      params.require(:storyline).permit(
        :name,
        :description
      )
    end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :is_current_user
  before_action :set_campaign, except: %i[index]

  def index
    add_breadcrumb("campaigns", campaigns_path, true)

    @pagy, @campaigns = pagy(current_user.campaigns.order(updated_at: :desc), items: params[:items])
  end

  def show
    add_breadcrumb("campaigns", campaigns_path)
    add_breadcrumb(@campaign.title, campaign_path(@campaign), true)
  end

  def new
    add_breadcrumb("campaigns", campaigns_path)
  end

  def edit
    add_breadcrumb("campaigns", campaigns_path)
  end

  def create
    @campaign.assign_attributes(campaign_params)
    if @campaign.save
      flash[:success] = "Campaign #{params[:action]}d"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @campaign.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @campaign.assign_attributes(campaign_params)
    if @campaign.save
      flash[:notice] = "Campaign #{params[:action]}d"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = @campaign.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @campaign.destroy
      flash[:notice] = "Campaign deleted"
    else
      flash[:error] = @campaign.errors.full_messages.to_sentence
    end
    redirect_to campaigns_path
  end

  private

  def set_campaign
    @campaign = params[:id] ? Campaign.find(params[:id]) : Campaign.new(user: current_user)
  end

  def campaign_params
    params.require(:campaign).permit(
      :title,
      :description
    )
  end
end

app/views/campaigns/_campaign.erb
<div id="<%= dom_id campaign %>" class="card bg-light border rounded border-secondary">
  <div class="card-body">
    <div>
      <h2>
        <%= link_to campaign.title, campaign_path(campaign), class: 'btn btn-link p-0' %>
      </h2>
      <p class="card-text"><%= campaign.description %></p>
    </div>
    <div class='campaign-card-nav'>
      <%= link_to 'View', campaign_path(campaign), class: 'm-1 btn btn-primary btn-sm', data: { turbo: false } %>
      <%= link_to 'Edit', edit_campaign_path(campaign), class: 'm-1 btn btn-secondary btn-sm', data: { turbo: false } %>
      <%= button_to 'Delete', campaign_path(campaign), method: :delete, class: 'm-1 btn btn-danger btn-sm', data: { turbo: false } %>
    </div>
  </div>
  <div class="card-footer campaign-card-footer">
    <small class="text-muted">Last updated <%= distance_of_time_in_words(campaign.updated_at, DateTime.now) %> ago</small>
  </div>
</div>

app/views/campaigns/_form.html.erb
<%= form_with model: @campaign, local: true, class: 'CampaignForm' do |form| %>
<h1>Create a New Campaign</h1>
  <div class='form-container m-2'>
    <div class="form-group m-2 text-center">
      <label for="#title">Campaign Title</label>
      <%= form.text_field :title, placeholder: "Campaign Title", class: "form-control" %>
    </div>

    <div class="form-group m-2 text-center">
      <label for="#description">Campaign Description</label>
      <%= form.text_area :description, placeholder: "Campaign Description", class: "text-area form-control", rows: 10 %>
    </div>

    <div class="form-group m-1 text-center">
      <%= form.submit  class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<%= render 'form' %>

app/views/campaigns/index.html.erb
<section class='Campaigns m-2'>
  <div class='page-header-center'>
    <h1>Your Campaigns</h1>
  </div>
  <div class="page-header-end campaign-subheader">
    <%= link_to '+ Add new', new_campaign_path, class: 'btn btn-primary' %>
  </div>
  <div id="campaigns_list" class="campaign-card-row">
    <%= render @campaigns %>
  </div>

  <%= render "shared/pagination" %>
</section>

app/views/campaigns/show.html.erb
<div class='Campaign'>
  <div class='header text-center'>
    <h1><%= @campaign.title %></h1>
  </div>
  <div class='body'>
    <div class='card bg-light border rounded border-secondary m-1'>
      <div class='card-header'>
        <h2>Sessions</h2>
      </div>
    </div>
    <div class='card bg-light border rounded border-secondary m-1'>
      <div class='card-header'>
        <h2>Campaign Details</h2>
      </div>
      <div class='card-body'>
        <div>
          <%= link_to 'Player Characters', campaign_player_characters_path(@campaign), class: 'card-link' %>
        </div>
        <div>
          <%= link_to 'Non-Player Characters', campaign_non_player_characters_path(@campaign), class: 'card-link' %>
        </div>
        <div>
          <%= link_to 'Cities', campaign_cities_path(@campaign), class: 'card-link' %>
        </div>
        <div>
          <%= link_to 'Factions', campaign_factions_path(@campaign), class: 'card-link' %>
        </div>
        <div>
          <%= link_to 'Storylines', campaign_storylines_path(@campaign), class: 'card-link' %>
        </div>
        <div>
          <%= link_to 'Quests', campaign_quests_path(@campaign), class: 'card-link' %>
        </div>
      </div>
    </div>
  </div>
</div>