config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#index"

  resources :campaigns do
    resources :player_characters, controller: "campaigns/player_characters"
    resources :non_player_characters, controller: "campaigns/non_player_characters"
    resources :cities, controller: "campaigns/cities"
    resources :factions, controller: "campaigns/factions"
    resources :storylines, controller: "campaigns/storylines"
    resources :quests, controller: "campaigns/quests"
  end
end

app/views/layouts/_breadcrumbs.html.erb
<% if @breadcrumbs.present? %>
  <div class="p-2" >
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <% @breadcrumbs.each do |bc|%>
          <li class="breadcrumb-item <%= bc[:active] == true ? "active" : nil %>">
            <% if bc[:active] == true %>
              <%= bc[:label].downcase %>
            <% else %>
              <a href="<%= bc[:path] %>"><%= bc[:label].downcase %></a>
            <% end %>
          </li>
        <% end %>
      </ol>
    </nav>
    <hr>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<div class='flash m-1'>
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= ['success', 'notice'].include?(name) ? "success" : "danger" %>" role="alert">
        <button id='flash-dismiss' type="button" class="close btn" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">x</span>
        </button>
        <%= msg %>
    </div>
  <% end %>
</div>

<script>
  $(function() {
    setTimeout(() => {
      $('.flash').slideUp()
    }, 5000);
  })
</script>

app/views/layouts/_topnav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand p-1" href="#">GmScreen</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to root_path, class: "nav-link" do %>
            Home
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to campaigns_path, class: "nav-link" do %>
            My Campaigns
        <% end %>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <%= link_to edit_user_registration_path, class: "nav-link" do %>
              My Account
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: "nav-link"  do %>
              Sign Out
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
              Sign Up
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link" do %>
              Sign In
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GmScreen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap');
    </style>
    <%#= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class='bg-light'>
    <div class='body-wrapper'>
      <%= render 'layouts/topnav' %>
      <%= render 'layouts/breadcrumbs' %>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>